image: maven:latest
#
build:
  stage: build
  script:
   - mvn install:install-file -Dfile=ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=11.2.0.4.0 -Dpackaging=jar compile
   - mvn clean package 

  
  
 

